#!/usr/bin/env bash
# Delete 82 remote branches whose PRs were merged into main.
# Run this locally with proper GitHub credentials:
#   chmod +x delete-merged-branches.sh && ./delete-merged-branches.sh
set -euo pipefail

BRANCHES=(
  "Wynillo-patch-1"
  "claude/add-campaign-mode-jbgKO"
  "claude/add-card-buff-selection-sqTJt"
  "claude/add-card-placeholders-hIadC"
  "claude/add-equipment-card-type-fmzp2"
  "claude/add-equipment-requirements-GcCwz"
  "claude/add-field-spell-cards-rQxrC"
  "claude/add-field-spell-values-khXbE"
  "claude/add-fusion-animation-uYU7v"
  "claude/add-log-download-button-p85ti"
  "claude/add-menu-background-frame-954nD"
  "claude/audit-retro-app-BtDvz"
  "claude/beautiful-heyrovsky"
  "claude/buff-atk-def-together-fdNhN"
  "claude/busy-hodgkin"
  "claude/card-atk-def-display-bi38A"
  "claude/card-colors-disabled-states-vV26p"
  "claude/center-battle-button-T6bim"
  "claude/charming-chatterjee"
  "claude/debug-mysterious-issues-kqk3Z"
  "claude/elastic-ptolemy"
  "claude/enhance-ai-intelligence-VDqUD"
  "claude/fix-back-button-dropdown-3dOTv"
  "claude/fix-battle-log-ZudBh"
  "claude/fix-battle-phase-test-IrOmq"
  "claude/fix-button-styling-yBbgm"
  "claude/fix-campaign-progression-w5TWY"
  "claude/fix-campaign-win-screen-dq0kQ"
  "claude/fix-card-stats-portrait-2qhbU"
  "claude/fix-color-alignment-Y3RjF"
  "claude/fix-dependencies-cleanup-0iJ9A"
  "claude/fix-download-duel-bugs-RQV1L"
  "claude/fix-duel-card-click-Peg6u"
  "claude/fix-duel-save-state-J8t9p"
  "claude/fix-duel-screen-issues-p3tuK"
  "claude/fix-effect-positioning-zMbCd"
  "claude/fix-effect-skip-flash-EfPpU"
  "claude/fix-fusion-system-TT1LI"
  "claude/fix-game-screens-music-Udu4k"
  "claude/fix-github-actions-uiw9X"
  "claude/fix-mobile-portrait-stats-Wbm2U"
  "claude/fix-music-starter-deck-RGb7N"
  "claude/fix-mysterious-effect-qOpdk"
  "claude/fix-savepoint-screen-TUrTA"
  "claude/fix-savestate-mechanics-3Tsfh"
  "claude/fix-shop-pack-cards-t1qX3"
  "claude/fix-sound-slider-reset-WHTJs"
  "claude/fix-summon-effects-8wVFw"
  "claude/fix-title-screen-tests-yZLyw"
  "claude/fix-vite-manualchunks-RvPN7"
  "claude/free-card-position-changes-etk4K"
  "claude/highlight-card-keywords-BtjZx"
  "claude/implement-sketch-JnI1l"
  "claude/improve-battle-ui-pKYmK"
  "claude/improve-card-list-Sam0p"
  "claude/improve-code-quality-2I4Aq"
  "claude/improve-code-quality-glaXy"
  "claude/improve-font-readability-zrUaD"
  "claude/improve-tcg-format-Pgc9y"
  "claude/improve-value-readability-ZDE6M"
  "claude/improve-victory-screen-nzO7G"
  "claude/long-press-fusion-mechanic-semmV"
  "claude/monster-color-styling-V5Iam"
  "claude/new-session-HkPPI"
  "claude/pensive-solomon"
  "claude/rebalance-shop-coins-Yw5Fi"
  "claude/refill-hand-cards-KKSP6"
  "claude/remove-log-download-OH8yb"
  "claude/rename-cards-pxXuP"
  "claude/reposition-back-button-A60wb"
  "claude/speed-up-card-effects-gNeXp"
  "claude/story-nodes-chapter-dropdown-b1XXg"
  "claude/tcg-expert-subagent-j6fE5"
  "claude/test-volume-controls-V9sBa"
  "claude/update-dependencies-IG1SP"
  "claude/update-docs-XcuiQ"
  "claude/vigorous-franklin-clean"
  "claude/yugioh-fusion-mechanics-78R3X"
  "claude/yugioh-fusion-rules-Z8IJE"
  "docs/fix-tcg-format-description"
  "fix/opponent-probe-404"
  "fix/tcg-folder-loader"
)

echo "Deleting ${#BRANCHES[@]} merged remote branches..."
DELETED=0
FAILED=0

for branch in "${BRANCHES[@]}"; do
  if git push origin --delete "$branch" 2>/dev/null; then
    echo "  ✓ Deleted: $branch"
    ((DELETED++))
  else
    echo "  ✗ Failed:  $branch"
    ((FAILED++))
  fi
done

echo ""
echo "Done. Deleted: $DELETED, Failed: $FAILED"
echo "Run 'git fetch origin --prune' to clean up local tracking refs."
