import type { IconType } from 'react-icons';
import {
  GiBearFace,
  GiBookCover,
  GiButterfly,
  GiCardDraw,
  GiCardPlay,
  GiCheckMark,
  GiCrossedSwords,
  GiFastForwardButton,
  GiFire,
  GiFireBowl,
  GiFireBreath,
  GiGears,
  GiHamburgerMenu,
  GiHearts,
  GiLightningTrio,
  GiPauseButton,
  GiPlayButton,
  GiPresent,
  GiShield,
  GiShoppingCart,
  GiSkullCrossedBones,
  GiSparkles,
  GiSpikedDragonHead,
  GiStack,
  GiStarShuriken,
  GiStonePile,
  GiTombstone,
  GiTwoCoins,
  GiVineLeaf,
  GiWaterDrop,
  GiWizardStaff,
} from 'react-icons/gi';

const GI_ICONS: Record<string, IconType> = {
  GiBearFace,
  GiBookCover,
  GiButterfly,
  GiCardDraw,
  GiCardPlay,
  GiCheckMark,
  GiCrossedSwords,
  GiFastForwardButton,
  GiFire,
  GiFireBowl,
  GiFireBreath,
  GiGears,
  GiHamburgerMenu,
  GiHearts,
  GiLightningTrio,
  GiPauseButton,
  GiPlayButton,
  GiPresent,
  GiShield,
  GiShoppingCart,
  GiSkullCrossedBones,
  GiSparkles,
  GiSpikedDragonHead,
  GiStack,
  GiStarShuriken,
  GiStonePile,
  GiTombstone,
  GiTwoCoins,
  GiVineLeaf,
  GiWaterDrop,
  GiWizardStaff,
};

export function resolveGiIcon(name: string): IconType | undefined {
  return GI_ICONS[name];
}
